### ISSUE TITLE
showSaveIcon: true, adds some space in table rows, but not in table headers.

### ISSUE THREAD

**Issue by Amitbhave** [godilite/editable#3]
showSaveIcon: true, adds one column in table rows, but not in table headers.
And as Flex: 1 is used in headers, if there are 4 headers, each will take total 1/4th of the space, but in rows, some space will go for the save icon.
Result:

![Screenshot_1601839050](https://user-images.githubusercontent.com/15723901/95025527-f2569e00-06a7-11eb-86ed-97cf9eff8dff.png)

**Comment by godilite** [comment]
Thank you @Amitbhave this issue is fixed temporarily in the new release v1.0.4. hence closed
